config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "prescriptions#index"
  # Routes for the Data_type resource:
  # CREATE
  get "/data_types/new", :controller => "data_types", :action => "new"
  post "/create_data_type", :controller => "data_types", :action => "create"

  # READ
  get "/data_types", :controller => "data_types", :action => "index"
  get "/data_types/:id", :controller => "data_types", :action => "show"

  # UPDATE
  get "/data_types/:id/edit", :controller => "data_types", :action => "edit"
  post "/update_data_type/:id", :controller => "data_types", :action => "update"

  # DELETE
  get "/delete_data_type/:id", :controller => "data_types", :action => "destroy"
  #------------------------------

  # Routes for the Record resource:
  # CREATE
  get "/records/new", :controller => "records", :action => "new"
  post "/create_record", :controller => "records", :action => "create"

  # READ
  get "/records", :controller => "records", :action => "index"
  get "/records/:id", :controller => "records", :action => "show"

  # UPDATE
  get "/records/:id/edit", :controller => "records", :action => "edit"
  post "/update_record/:id", :controller => "records", :action => "update"

  # DELETE
  get "/delete_record/:id", :controller => "records", :action => "destroy"
  #------------------------------

  devise_for :patients
  # Routes for the Patient resource:
  # READ
  get "/patients", :controller => "patients", :action => "index"
  get "/patients/:id", :controller => "patients", :action => "show"


  # Routes for the Prescription resource:
  # CREATE
  get "/prescriptions/new", :controller => "prescriptions", :action => "new"
  post "/create_prescription", :controller => "prescriptions", :action => "create"

  # READ
  get "/prescriptions", :controller => "prescriptions", :action => "index"
  get "/prescriptions/:id", :controller => "prescriptions", :action => "show"

  # UPDATE
  get "/prescriptions/:id/edit", :controller => "prescriptions", :action => "edit"
  post "/update_prescription/:id", :controller => "prescriptions", :action => "update"

  # DELETE
  get "/delete_prescription/:id", :controller => "prescriptions", :action => "destroy"
  #------------------------------

  devise_for :doctors
  # Routes for the Doctor resource:
  # READ
  get "/doctors", :controller => "doctors", :action => "index"
  get "/doctors/:id", :controller => "doctors", :action => "show"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>FinalProjectEhr</title>


  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">FinalProjectEhr</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/data_types">Data Types</a></li>
          <li><a href="/records">Records</a></li>
          <li><a href="/patients">Patients</a></li>
          <li><a href="/prescriptions">Prescriptions</a></li>
          <li><a href="/doctors">Doctors</a></li>
          <li><a href="/rails/info">Sitemap</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_doctor.present? %>
            <li>
              <a href="/doctors/edit">
                <%= current_doctor.email %>
              </a>
            </li>

            <li>
              <a href="/doctors/sign_out" data-method="delete" rel="nofollow">
                Sign Out
              </a>
            </li>
          <% else %>
            <li>
              <a href="/doctors/sign_up">
                Sign Up
              </a>
            </li>

            <li>
              <a href="/doctors/sign_in">
                Sign In
              </a>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>